
export enum TaskEventType {
    Create = 'create',
    Assign = 'assign',
    Rename = 'rename',
    ClientSignDoc = 'client-sign-doc',
    OrgProceed = 'start-proceeding',
    RequestClientSign = 'request-client-sign',
    UnrequestClientSign = 'unrequest-client-sign',
    RequestClientInputFields = 'request-client-fields',
    ClientSubmit = 'client-submit',
    ClientDownloadDoc = 'client-download-doc',
    Complete = 'complete',
    Archive = 'archive',
    StatusChange = 'status-change',
    MoveBackToDo = 'move-back-to-do',
    FieldSchemaChange = 'field-schema-change',
    FieldValuesChange = 'field-value-change',
    AddDoc = 'add-doc',
    DeleteDoc = 'delete-doc',
    GenDoc = 'gen-doc',
    Comment = 'comment',
}
