
export enum ZeventName {
    TaskCreated = 'task-created',
    TaskCreatedByRecurringly = 'task-created-recurringly',
    TaskAssigned = 'task-assigned',
    TaskRenamed = 'task-renamed',
    TaskStatusToInProgress = 'task-status-started',
    TaskStatusCompleted = 'task-status-completed',
    TaskStatusArchived = 'task-status-archived',
    TaskStatusMovedBackToDo = 'task-moved-back-todo',
    TaskStatusAwaitClient = 'task-await-client',
    TaskFormSchemaChanged = 'task-form-schema-changed',
    TaskFieldValueChanged = 'task-field-value-changed',
    TaskAddedDoc = 'task-added-doc',
    TaskDeletedDoc = 'task-deleted-doc',
    TaskGenedDoc = 'task-gened-doc',
    RequestClientSignDoc = 'request-client-sign-doc',
    UnrequestClientSignDoc = 'unrequest-client-sign-doc',
    RequestClientFillForm = 'request-client-fill-form',
    ClientSignedDoc = 'client-signed-doc',
    ClientSubmittedForm = 'client-submitted-form',
    ClientDownloadedDoc = 'client-downloaded-doc',
    TaskComment = 'task-comment',
    SupportMessage = 'support-message',
}
