import React from 'react';
import styled from 'styled-components';
import { Typography } from 'antd';
import { Logo } from 'components/Logo';
const ContainerStyled = styled.div`
padding: 2rem 1rem;
margin: 1rem auto;
text-align: left;
width: 100%;
max-width: 900px;
font-size: 0.9rem;

h2 {
  font-size: 1.3rem;
}

h3 {
  font-size: 1.1rem;
}
`;
const { Title } = Typography;
const TermAndConditionPage = () => <>
  <ContainerStyled>
    <div style={{ width: '100%', textAlign: 'center', marginBottom: '2rem' }}><Logo /></div>
    <Title style={{ textAlign: 'center' }}>Techseeding Pty Ltd - Terms and Conditions</Title>
    <Title level={2}>1. Scope</Title>
      <p>These general terms apply to all professional relationships between ZeeWorkFlow and its Client, notwithstanding any Client’s general terms even if more recent, unless explicitly accepted, totally or partially, in writing by ZeeWorkFlow.</p>
      <p>In case of contradiction between the Engagement Letter and the General Terms, the Engagement Letter shall prevail.</p>
      <Title level={2}>2.Formation of the services contract</Title>
      <p>The services Contract between ZeeWorkFlow and the Client is deemed to have been entered into either when ZeeWorkFlow receives the Engagement Letter, duly signed by the Client, or at the moment ZeeWorkFlow starts to perform any Services upon request of the Client, if this takes place at an earlier moment. As long as ZeeWorkFlow does not receive any Engagement Letter duly signed by the Client, all professional relationships between ZeeWorkFlow and the Client will in any case be governed by the Services Contract, as from the moment that and insofar as such Services Contract has been delivered to the Client either by letter, telefax, email, verbal or by hand, against acknowledgement of the receipt.</p>
      <Title level={2}>3.Information supplied by the client to ZeeWorkFlow</Title>
      <p>To enable ZeeWorkFlow to perform the Services, the Client shall provide it in due time with assistance as well as with correct, complete and reliable data and documents, even if such information originates from third parties. This undertaking is applicable irrespective if the Client makes such data and documents available to ZeeWorkFlow in so called “hard-copy” format or through the ZeeWorkFlow platform.</p>
      <p>ZeeWorkFlow has no obligation to verify the completeness, accuracy and reliability of such data and documents.</p>
      <p>ZeeWorkFlow may claim additional fees and/or outlays resulting from any delay in performing the Services, as a consequence of the Client having failed to comply with the provisions of this.</p>
      <p>The Client shall inform ZeeWorkFlow of any information or developments which may come to its notice and which might have a bearing on the Services.</p>
      <p>The Client will provide ZeeWorkFlow with copies of all above mentioned data and documents or shall communicate such data and documents through our platform. The Client undertakes to keep the original data and documents and undertakes to keep them safe. If necessary of the performance of the Services, data and documents are provided in original by the Client to ZeeWorkFlow, the Client must keep a copy thereof.</p>
      <p>ZeeWorkFlow may rely on any instructions or requests made or notices given or information supplied, whether orally or in writing, by any person whom it knows to be or reasonably believes to be authorized by the Client to communicate with it for such purposes.
ZeeWorkFlow may receive information from the Client or from other sources in the course of delivering the Services.</p>
      <Title level={2}>4.Performance of the engagement</Title>
      <p>ZeeWorkFlow decides how and by whom the Services will be performed. The Services shall be delivered with reasonable skill and care based on the information supplied to us. Where individuals to be involved in delivering the Services are named in the Engagement Letter, ZeeWorkFlow shall use reasonable endeavours to ensure that they are effectively involved. ZeeWorkFlow may substitute those identified for others of equal or similar skills.</p>
      <p>Our employees are and remain in all respects employees of ZeeWorkFlow. We are responsible for the payment of the wages, social contributions, any contributions relating to any other social regulation and any other legal or other liabilities which we agreed upon with our staff or which the law obliges us to pay. If the Client gives instructions to our employees, such instructions must be expressly and specifically defined in the Services Contract and may not erode in any way ZeeWorkFlow’ authority as an employer or, in case such instructions relate to welfare at work such instructions may not intervene in the existing agreements between ZeeWorkFlow and its employees, which are and remain an exclusive matter of ZeeWorkFlow.</p>
      <p>The approach, method of working or scope of the mission and/or resulting activities can, from time to time, be modified or extended by mutual agreement. If such modification or extension results in additional work, ZeeWorkFlow shall inform the Client. The case arising, additional fees and outlays can be charged to the Client.</p>
      <p>ZeeWorkFlow shall not be under any obligation to update any advice, or any product of the Services, oral or written, for events occurring after the advice, report or product concerned has been issued in final form except where we have expressly agreed to provide such an update during the term or our engagement as a result of changes to e.g. regulation, jurisprudence or doctrine.</p>
      <p>The Client remains notably responsible for:</p>
      <ul>
        <li>the management, conduct and operation of its business and affairs;</li>
        <li>making decisions which could possibly influence the performance of our services or the result thereof;</li>
        <li>making decisions as to what extent Client wishes to rely on our advice, recommendations and other results of our Services, on their use and the implementation (if any) necessary with regard to</li>
      </ul>
      <p>the performance of our Services, including the evaluation of the adequacy of the results of the Services performed for the Client’s benefit and accepting responsibility for the actions, if any, to be taken arising from the results of the Services.</p>
      <p>Client management will designate a Project sponsor who has the requisite skills and competencies for overseeing the services being provided.</p>
      <p>Unless otherwise explicitly agreed upon in writing, the performance of the engagement does not authorize ZeeWorkFlow to represent the Client. Such representation authority requires a specific power of attorney, in writing, to be given by the Client to ZeeWorkFlow, and accepted by the latter.</p>
      <Title level={2}>5.Access to and use of the ZeeWorkFlow platform</Title>
      <p>In the event that the Client gains access to the ZeeWorkFlow platform for its Authorized Users, the following applies:</p>
      <p>Client register as a user in our platform to authorise ZeeWorkFlow to be the accountant and tax agent to deal with all the tasks set up in each portfolio which is under the user’s name. One user can authorise multiple portfolios and the user may be different from each portfolio’s person or director/public officer of an entity. All the correspondents between each user and us regarding all portfolios are confirmed by email which is registered at the same time as the user.</p>
      <p>The Client and its Authorized Users are only granted “read only” access, except in the case of customized management reporting. Hence, the Client and its Authorized Users can only upload data on the ZeeWorkFlow platform via a unique inbox upload system or via web scanning and can only consult such data without being entitled to change, adapt, or delete the data.</p>
      <p>In the event that ZeeWorkFlow provides the Client with access to a customized management reporting tool the Client and its Authorized Users are solely responsible for the use of this tool and the data they enter in the customized management reporting tool. The Client acknowledges and accepts that ZeeWorkFlow does not warrant, nor can be held accountable for the use (data entry included) of this tool by the Client and its Authorized Users.</p>
      <p>The Client acknowledges and accepts that it is the responsibility of the Client and its Authorized Users to take suitable steps to prevent that unauthorized users gain access to the ZeeWorkFlow platform, whereby, amongst other measures, they are to assume responsibility for maintaining the confidentiality of their login and password vis-à-vis each other and third parties and for not releasing such information to any such outside parties.</p>
      <p>The data are non-transferable and shall not be used outside the organization of the Client and its Authorized Users. It shall be incumbent on the Client to prohibit the use of the ZeeWorkFlow platform by any (legal) person other than the Client and/or its Authorized Users and for any purposes other than those specified within the context of the contracted Services. The Client is not entitled to assign or transfer rights and/or duties to third parties (including to any subsidiary company, parent company, stockholders, agents, representatives, or subcontractors) without prior written consent from ZeeWorkFlow. The platform only allows one unique email per each Authorized user, and the user is responsible on behalf of all the portfolios which are under the Authorized user.</p>
      <p>It shall further be incumbent on the Client to ensure that the data be accurate, complete, and reliable, also in the case of information supplied by the Authorized Users, by third parties, or scrutinized by the Client himself. It shall be incumbent on the Client to invariably save and keep an original copy of all of the data, to make a back-up thereof at regular intervals, and to save and safeguard them by one or several secured venues. ZeeWorkFlow shall under no circumstance be held liable for any loss of, or damage to, data or for ensuring that damaged data be restored and provided to the Client.</p>
      <p>The Client acknowledges and accepts that ZeeWorkFlow does not guarantee that the ZeeWorkFlow platform is virus-proof and that ZeeWorkFlow cannot be held responsible and/or liable for any and all loss(es) or damage(s) caused by any virus. The ZeeWorkFlow platform contains ‘links’ to other websites that are not property of ZeeWorkFlow. We caution and strongly urge the Client and every Authorized User to use his/her own reliable, adequate and appropriate anti-virus protection system.</p>
      <p>The Client undertakes, both on its own behalf and on behalf of its Authorized Users, to fully abide by the policy, the rules and regulations, and directives as established by ZeeWorkFlow with reference to security, technology, and risk management, as well as with reference to the use of the ZeeWorkFlow platform. In the event that the Client finds himself not in agreement with the changed or new policy, the rules and regulations, and directives as stated, it shall be incumbent on him to inform ZeeWorkFlow without delay of its disagreement, at which time ZeeWorkFlow shall be entitled to rescind the Client’s user right and that of its Authorized Users.</p>
      <p>Furthermore, the Client agrees to inform ZeeWorkFlow without delay of any and all situations or actions which the Client suspects or knows might or could compromise the security of the ZeeWorkFlow platform, such as unauthorized access to the password and login (“Login Data”) of an Authorized User.</p>
      <p>The Client accepts that ZeeWorkFlow shall have full access to the ZeeWorkFlow platform and to all functionalities thereof. As such, the Client acknowledges that ZeeWorkFlow shall be entitled to consult, use, modify, adapt, or delete the data.</p>
      <p>ZeeWorkFlow recognizes the importance of a permanent and effective control on the confidentiality of the information on the ZeeWorkFlow platform and, hence, has taken several measures to protect and secure such information against unauthorized access. The ZeeWorkFlow platform is configured in such a way that access to it requires a complex password to serve in the authentication of Authorized Users, that firewalls control the access to the system, and that data is exchanged in a secured (encrypted) fashion.</p>
      <p>Although ZeeWorkFlow has taken reasonable steps to safeguard the continuity of the ZeeWorkFlow platform, ZeeWorkFlow provides no warranty and assumes no liability whatsoever regarding suspension, interruption or temporary unavailability of the ZeeWorkFlow platform.</p>
      <p>The ZeeWorkFlow platform is accessible via a web browser. As is the case with all other internet applications, technical factors such as bandwidth, network configurations, and laptop browser settings may affect the speed and the accessibility of the ZeeWorkFlow platform.</p>
      <p>In view of such considerations, ZeeWorkFlow cannot guarantee the Client and the Authorized Users constant availability of access to the ZeeWorkFlow platform at all times.</p>
      <p>ZeeWorkFlow does not offer any guarantee(s) or warranty(s) related to the possible incompatibility with, disruption of, or damage to the computers of the Authorized Users caused as a result of the latter’s browser settings and, furthermore, rejects any and all guarantee(s) with reference to the reliability of the operation and functioning of the Authorized Users’ browser in combination with the ZeeWorkFlow platform. Certain risks are inherent in the transmission of data over the Internet and in the technical processes required for such transmissions.</p>
      <p>ZeeWorkFlow reserves the right to suspend, restrict, block, remove, or de-activate access to the ZeeWorkFlow platform for any reason whatsoever (such as, but not limited to, maintenance, software adaptations, etc.), as well as in any and all instances where ZeeWorkFlow suspects, or has gained knowledge, that the Client or Authorized Users are not duly abiding by their undertakings and obligations, either failing wholly or performing unsatisfactorily or being late in their compliance, or in the event of unauthorized use of the Web platform by the Client or its Authorized Users.</p>
      <p>The user right(s) granted to the Client and its Authorized Users shall remain valid for, and be restricted to, the duration of the Services only, unless explicitly agreed to otherwise.</p>
      <p>On termination of the Services, or on termination of the business relationship, the Client’s user right and the right of its Authorized Users to the ZeeWorkFlow platform shall be rescinded with immediate effect and without prior notice. In such event, ZeeWorkFlow shall be fully entitled to block, remove, or de-activate the Client’s and its Authorized Users’ access, as well as all related accounts.</p>
      <p>In the event that the Client wholly or partially fails to abide by one of its undertakings and obligations with regard to the ZeeWorkFlow platform and, as a result thereof, legal action has been, or is about to be, instituted by a third party against ZeeWorkFlow, it shall be incumbent on the Client to hold ZeeWorkFlow harmless from all loss(es) and damage(s), expenditures and liabilities sustained by ZeeWorkFlow, resulting and forth flowing from, or related to, such failure and such action.</p>
      <Title level={2}>6.Remote access and use of e-mail</Title>
      <p>ZeeWorkFlow is authorized to make use of Your local network and Your internet in order to connect to the ZeeWorkFlow network (also called “Remote Access via Internet “) during the performance of the Services. Immediately after connecting to Your local network, we will establish a direct connection (known as a VPN connection), which will create a separate network from your network. Any associated risks will be restricted to a minimum because of the security measures that we take (including a firewall, a virus scanner and anti-spyware scanner).We do not accept any liability for any damages resulting from the use of Remote Access via the Internet.</p>
      <p>ZeeWorkFlow is allowed to communicate to You by electronic mail. Consequently, You accept the risks inherent to this method of communication (including the security risks of interception of or unauthorized access to such communications, the risks of corruption of such communications and the risks of viruses or) and You shall perform virus checks.</p>
      <Title level={2}>7.Confidentiality</Title>
      <p>ZeeWorkFlow shall treat information obtained either prior to or in the course of delivering the Services as confidential according to the legal and professional confidentiality standards applicable to accountants and tax advisers. This clause shall not prohibit ZeeWorkFlow's disclosure of information if it is so required or permitted pursuant to legal or professional regulations, e.g., in disciplinary, civil or criminal proceedings or in the context of anti-money laundering legislation.</p>
      <p>The Client acknowledges and agrees that information related to the Services (including confidential information) may be disclosed to ZeeWorkFlow International and other ZeeWorkFlow Persons that assist us:</p>
      <ul>
        <li>in the execution of the Services;</li>
        <li>to support the maintenance of quality and professional standards in the delivery of services (e.g. through the involvement of professional practice and policy departments, the participation in quality assurance measures or the establishment and maintenance of knowledge databases);</li>
        <li>in the execution of client and engagement acceptance procedures
        (including but not limited to potential conflicts of interest checks)
For the execution of the Services Contract, we may make use of computer software in order to facilitate the efficient management of data. Consequently, data which is supplied by You may be transferred to computer servers which are operated outside Belgium with the implementation of adequate access controls and under the authority of member firms belonging to the ZeeWorkFlow network.</li>
      </ul>
      <Title level={2}>8.Product of the services</Title>
      <p>Any product of the Services released to You in any form or medium shall be supplied by us on the basis that it is for Your benefit and information only and that it shall not be copied, referred to or disclosed, in whole or in part, unless this is required by Belgian legislation (in such case You will inform us prior to any disclosure). The Services shall be delivered on the basis that You shall not quote our name or reproduce our logo in any form or medium without our prior written consent.</p>
      <Title level={2}>9.Intellectual property</Title>
      <p>ZeeWorkFlow shall retain ownership of the copyright and all other intellectual property rights in the product of the Services, and ownership of our working papers. The Client shall acquire ownership of any product of the Services in its tangible form on payment of our Charges for any such product. For the purposes of the performance of our services, we shall be entitled to use, develop or share with each other knowledge, experience and skills of general application gained through performing the Services.</p>
      <p>Every and all copyright(s) and all other intellectual property right(s) and every and all similar rights on the ZeeWorkFlow platform shall be and will remain the exclusive property of ZeeWorkFlow or its licenser(s). The Client is not authorized to grant or sell licenses with regard to ZeeWorkFlow platform or make any other profitable use of the ZeeWorkFlow platform. The Client is not authorized to decompile or disassemble ZeeWorkFlow platform nor to subject it to reverse engineering, to change it in any way or to break in or gain access to areas of the ZeeWorkFlow platform for which ZeeWorkFlow did not grant access.</p>
      <Title level={2}>10.Prohibition of hiring of ZeeWorkFlow’ employees</Title>
      <p>During the whole term of the Services Contract, and for a period of 12 months as from the termination thereof, regardless of the reason of the termination, the Client shall not engage any member of the staff or independent worker of ZeeWorkFlow, directly or indirectly involved in the execution of the Services, or let him/her carry out activities beyond the framework of the agreement between ZeeWorkFlow and the Client, unless prior agreement has been obtained in writing from ZeeWorkFlow.</p>
      <p>Any infringement of this prohibition shall result in the payment of a once-only compensation of 3 months employee’s salary plus superannuation.</p>
      <p>The same compensation is due by the Client who, with the intention to by-pass this prohibition, obtains the same result in any other way.</p>
      <Title level={2}>11.Our charges</Title>
      <p>ZeeWorkFlow shall render fee notes in respect of the Services comprising fees, outlays and taxes thereon (where appropriate) (hereafter "our Charges"). Our Charges and any special payment terms shall be set out in the Engagement Letter.</p>
      <p>Unless otherwise explicitly agreed upon in writing, fees shall be based on the degree of responsibility of the persons involved in delivering the Services, their skill and time spent in performing the Services. Outlays will include both directly incurred costs, including expenses incurred with third parties, and an amount that may be determined as a percentage of the fees, to cover incidental expenses, which are not charged directly to the engagement.</p>
      <p>Our Charges may differ from estimates or quotations that may have been supplied, for example where additional fees and outlays arise from any delay as a result of failure to supply information required to enable ZeeWorkFlow to perform the Services.</p>
      <p>Where ZeeWorkFlow is required to provide information in respect of the Client pursuant to a regulatory request, requirement or through any form of legal proceedings, the Client agrees to reimburse ZeeWorkFlow for the costs ZeeWorkFlow and its personnel incur in relation to such requirement, request or proceeding, where ZeeWorkFlow’ actions were not also the subject of such requirement, request or proceeding.</p>
      <Title level={2}>12.Payment and payment terms</Title>
      <p>The Client shall pay our Charges, without any right of deduction or set-off, within the term indicated on the fee notes, but by no means later than thirty days after receipt of the fee notes. The date of receipt of the fee notes is fixed on the first day, following the date mentioned on the fee notes.</p>
      <p>Unless otherwise explicitly agreed upon in writing, any payments by the Client are to be made in Euros.</p>
      <p>In case of default, ZeeWorkFlow is entitled to charge interest on any outstanding balances at the interest rate of 4% per annual.</p>
      <p>By virtue of the law referred to above, any overdue payment will also entitle ZeeWorkFlow, without issuing any default notice, to claim lump-sum damages for recovery outlays, which will amount to 15% of the fee notes except if ZeeWorkFlow can prove that higher damages have been incurred.</p>
      <p>Non-payment of our Charges by the expiry date entails the immediate collectability of all outstanding invoices, even the non-due invoices, without us having to take into account previously authorized payment conditions.</p>
      <p>If the Services Contract is terminated or suspended, ZeeWorkFlow shall be entitled to payment for outlays incurred to that time and to payment of fees for work done, plus taxes thereon (where appropriate). The fees for work done shall in this event be calculated by reference to the parameters referred to in article 8 of these General Terms, applicable at the time of performance of our Services.</p>
      <p>Where there is more than one addressee of the Engagement Letter, unless provision is made in the Engagement Letter for payment of our Charges by one of the addressees or by a third party, all of the addressees shall each be fully jointly and severally liable to pay our Charges, as well as any related interest and damages.</p>
      <Title level={2}>13.Knowledge and conflicts</Title>
      <p>The Engagement Team shall not be required, expected or deemed to have knowledge of any information known to Other ZeeWorkFlow Persons which is not known to the Engagement Team or be required to obtain such information from Other ZeeWorkFlow Persons.</p>
      <p>The Engagement Team shall not be required to make use of or to disclose to You any information, whether known to them personally or known to Other ZeeWorkFlow Persons, which is confidential to another client.</p>
      <p>ZeeWorkFlow Persons may provide services or be approached to provide services for one or more parties with interests conflicting with Your interests or that have interests that compete with Yours (“Party or Parties with a Conflict of Interest”). If You know or become aware that a ZeeWorkFlow Person is advising or proposing to advise a Party or Parties with a Conflict of Interest, You must inform us promptly.</p>
      <p>ZeeWorkFlow persons are and remain free to provide services to a Party or Parties with a Conflict of Interest. If the interests of the Party or Parties with a Conflict of Interest, specifically and directly with regard to the Services, are in conflict with Your interests and You have informed us thereof, then:</p>
      <ul>
        <li>The Engagement Team shall not provide services to the Party or Parties with a Conflict of Interest; and</li>
        <li>Other ZeeWorkFlow persons shall only provide services to the Party or Parties with a Conflict of Interest when adequate Barriers have been implemented. The effectiveness of these Barriers means that we have taken sufficient steps to avoid any real risks of damaging our confidential relationship of trust with You.</li>
      </ul>
      <Title level={2}>14. Limitation of liability</Title>
      <p>The liability of ZeeWorkFlow in connection with the Services Contract is limited in accordance with the provisions of article 14.1.</p>
      <h3>14.1 The aggregate liability of all ZeeWorkFlow Persons towards Client,</h3>
      <ul>
        <li>arising in any way and on any basis, and irrespective of its legal basis;</li>
        <li>for any damage arising from or in connection with the Services Contract;</li>
        <li>regardless of the cause of loss or damage, including our negligence and serious fault;</li>
      </ul>
      <p>is limited to an amount of 1 (one) time the fees charged by ZeeWorkFlow for the delivery of the Services . However, if the Services relate to monthly, quarterly or yearly periodical activities, our aggregate liability, as defined above, will be limited to an amount of 1 (one) times the fees charged by ZeeWorkFlow for the periodical activities executed over the last year.</p>
      <p>The limitation of liability as set out above is not applicable in the event that ZeeWorkFlow has committed a fault with fraudulent intent.</p>
      <p>ZeeWorkFlow Persons cannot be held liable for indirect damages, such as but not limited to, financial and commercial losses, loss of profits, increase of general costs, interruption of the planning, disturbances and glitches in (accounting)software, loss of the expected profit, capital, clients, etc.</p>
      <p>This article 14 does not prejudice in any way the exclusion and limitation of our liability with respect to ZeeWorkFlow platform as described in article 5.</p>
      <p>Where more than one addressee has been indicated for the delivery of the Services, the limitation on our liability agreed in article 14.1 applies to all of them jointly and shall be apportioned by them amongst them. No addressee shall dispute or challenge the validity, enforceability or operation of this clause on the ground that no such apportionment has been so agreed or on the ground that the agreed share of limitation amount apportioned to any addressee is unreasonably low.</p>
      <Title level={2}>15. Suspension and termination</Title>
      <p>If the Client is in breach of either executing or fulfilling correctly and/or in due time any of its obligations, ZeeWorkFlow is entitled to suspend the performance of the Services until the Client will have fully complied with its obligations. ZeeWorkFlow is also entitled to suspend the performance of the Services if, for any other engagement contracted with ZeeWorkFlow, the Client either has not executed, or has executed its obligations partially, incorrectly or with delay. ZeeWorkFlow will under all circumstances remain entitled to the payment of its Charges as set out in article 11 of these General Terms.</p>
      <p>Either party can terminate the Services Contract by giving a reasonable notice term. Notices must be notified to the other Party (ies) by registered mail. In case of immediate termination by the Client without observance of the notice term, he shall pay a compensation to ZeeWorkFlow equal to the half of the fees for aforesaid notice term.</p>
      <p>However, the Client is entitled to terminate the Services Contract immediately without observance of any notice term and without payment of any compensation to ZeeWorkFlow, if:</p>
      <ul>
        <li>ZeeWorkFlow fails seriously in the performance of their liabilities;</li>
        <li>in case of composition, bankruptcy, winding-up or liquidation of ZeeWorkFlow.</li>
      </ul>
      <p>ZeeWorkFlow is entitled to terminate the Services Contract immediately without notice term, without proof of default, without being liable for any compensation whatsoever, and without prior judicial intervention in any of the following cases:</p>
      <ul>
        <li>the Client commits a breach of contract, such as, but not limited to, the provision of incorrect or incomplete information to ZeeWorkFlow, the absence of payment of the fees after sending of a formal notice, or the non-respect of the undertakings with regard to ZeeWorkFlow platform;</li>
        <li>ZeeWorkFlow is no longer allowed to provide the Client with services as a result of mandatory rules such as, but not limited to, legislation relating to the independence of the network of the auditor and to anti-money laundering;</li>
        <li>in case of composition, bankruptcy, winding-up or liquidation of the Client.</li>
      </ul>
      <p>ZeeWorkFlow will in all circumstances remain entitled to the payment of the Charges relating to work done and of the fee notes for the services performed, as set out in article 11 of these General Terms.</p>
      <p>If the Client breaches any of the obligations under the Services Contract and there is any claim made or threatened against ZeeWorkFlow by a third party; the Client shall compensate ZeeWorkFlow and hold ZeeWorkFlow harmless for any loss, damage, expense or liability incurred by ZeeWorkFlow, which results from or arises from or is connected with any such breach and any such claim.</p>
      <Title level={2}>16. Disputes</Title>
      <p>Any complaint related to the Services performed or to our Charges must be communicated in writing to ZeeWorkFlow, either within 30 days as from the sending date, by ZeeWorkFlow, of the information and/or documents disputed by the Client, or within 30 days upon discovery of the mistake, provided that the Client demonstrates that such mistake could not have been discovered earlier. Any such dispute does not suspend the Client's payment obligations.</p>
      <p>If a complaint is considered to be well-founded, ZeeWorkFlow may decide:</p>
      <ul>
        <li>either, to correct, free of any charge, the Services performed; or</li>
        <li>to perform again, totally or partially, the Services disputed; or</li>
        <li>to cancel, totally or partially, the engagement with a proportional refund of the Charges paid by the Client; or</li>
        <li>to adjust the amount of the fee notes issued.</li>
      </ul>
      <p>Unless explicitly otherwise agreed upon in writing, the period during which any complaint can be made by the Client against ZeeWorkFlow expires six months as from the moment the client knew of the facts giving rise to said complaint, or should reasonably have known thereof.</p>
      <Title level={2}>17. Processing of personal data</Title>
      <p>This article applies to the treatment of personal data in connection with the Services and/or the Engagement Letter.</p>
      <p>You warrant that the personal data which You transfer to ZeeWorkFlow (i.e. ZeeWorkFlow, other ZeeWorkFlow Persons and/or third parties supporting ZeeWorkFlow) in connection with the execution of the Services and the Engagement Letter, will be processed by You in accordance with the provisions and principles of the GDPR.</p>
      <p>ZeeWorkFlow acts as controller in connection with the Services, whereby ZeeWorkFlow also has to comply with certain legal obligations and regulations. ZeeWorkFlow will process the received personal data as controller based on the Engagement Letter and/or based on one of the legal obligations.</p>
      <p>ZeeWorkFlow will take appropriate technical and organizational measures in order to protect the personal data against unauthorized or unlawful processing and against accidental loss, destruction of or damage to the personal data.</p>
      <p>ZeeWorkFlow can transfer personal data for the execution of the Services to other ZeeWorkFlow Persons and/or to third parties that support ZeeWorkFlow who will also take necessary and appropriate technical and organizational measures to protect personal data. Moreover, the received personal data can, amongst others, be communicated to and used by other ZeeWorkFlow Persons and/or third parties that support ZeeWorkFlow in view of compliance and regulatory requirements (amongst others anti-money laundering legislation), risk management and quality control of the Services delivered by ZeeWorkFlow, as well as for client and relation management.</p>
      <p>In the event of loss of personal data, data breach or performance of a data protection impact assessment, You will respond to any reasonable request for assistance from ZeeWorkFlow.</p>
      <p>Parties shall notify each other promptly: (i) upon receiving a request from a data subject, or if they receive any claim, complaint or allegation relating to the processing of personal data; (ii) upon becoming aware of any breach leading to the destruction, loss or unlawful disclosure of personal data in their possession.</p>
      <p>You will notify ZeeWorkFlow promptly if You acquire knowledge of an infringement regarding the processing of the aforementioned personal data.</p>
      <Title level={2}>18. Independence of the ZeeWorkFlow network</Title>
      <p>We have the responsibility to keep the independence of our clients.</p>
      <Title level={2}>19. Waiver and severability</Title>
      <p>Any failure by ZeeWorkFlow to enforce one of its rights or prerogatives under the Services Contract, or any failure by ZeeWorkFlow to react to a default or breach by the Client of all or any parts of the provisions of the Services Contract shall not constitute a waiver by ZeeWorkFlow of any of its rights there under.</p>
      <p>Each clause or term of the Services Contract constitutes a separate and independent provision. If any of the provisions of the Services Contract is void or unenforceable, the remaining provisions shall continue in full force and effect.</p>
      <Title level={2}>20. Circumstances beyond your or our control</Title>
      <p>ZeeWorkFlow is not bound to carry out its obligations mentioned under this Services Contract if its enforcement is hindered by an event of force majeure. Following circumstances shall be considered as force majeure, without being limitative: a state intervention, weather conditions, breakdowns and disruptions in telecommunication and internet connections, disruptions in (accountancy) software, delay or breach of ZeeWorkFlow’s subcontractors in the performance of their obligations or strikes or similar circumstances which results in the Services not being provided or being provided with delay and/or being provided partially. ZeeWorkFlow is under no obligation to prove that such circumstances were unforeseeable and unavoidable.</p>
      <Title level={2}>21. Applicable law and jurisdictions</Title>
      <p>The professional relationships between the Parties to which these General Terms apply will be governed exclusively by law. All disputes related thereto will be submitted exclusively to the courts within the judicial area in which ZeeWorkFlow has its registered office.</p>
  </ContainerStyled>
</>;  

TermAndConditionPage.propTypes = {};

TermAndConditionPage.defaultProps = {};

export default TermAndConditionPage;
